language: go

go:
- 1.14

script: 
#- export OLDPATH=`pwd` && mkdir -p $GOPATH/src/golang.org/x/ && cd $GOPATH/src/golang.org/x/ && git clone https://github.com/golang/lint.git && cd $GOPATH/src/golang.org/x/lint/golint && go install && cd $OLDPATH  && golint ./...
#- go build -o edgeadm cmd/edgeadm/edgeadm.go
- ./golint.sh

notifications:
    webhooks: http://106.55.135.32:9990/webhook
