language: go

go:
- 1.14

script:
- gofmt -s cmd/ 
#- go build -o edgeadm cmd/edgeadm/edgeadm.go
- chmod +x golint.sh 
- bash golint.sh

notifications:
    webhooks: http://106.55.135.32:9990/webhook
