language: go

go:
- 1.14

jobs:
    include:
        - stage: go format
          script: gofmt -s cmd/
        - stage: go lint
          script: chmod +x golint.sh
        #- script: bash golint.sh
        - script: echo "test"
        - stage: go test
          if: 1=1
          script: skip
        - stage: go build
          script: go build -o edgeadm cmd/edgeadm/edgeadm.go

notifications:
    webhooks: http://106.55.135.32:9990/webhook
