baseConfig:
  organization: edge
  etcd:
    etcdServers: https://10.0.4.23:2379
  imageRegistry:
    isSecureRegistry: false
    registryServer: ccr.ccs.tencentyun.com
    registryNamespace: edgecluster

selfConfig:
  nodeHosts:
    - ip: 127.0.0.1
      domain: registry.tkeedge.com
    - ip: 127.0.0.2
      domain: registry.tkeedge.com
  dockerConfig:
    insecureRegistries:
      - ccr.ccs.tencentyun.com
    registryMirrors:
      - ccr.ccs.tencentyun.com

