//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The SuperEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	sitesuperedgeio "github.com/superedge/superedge/pkg/site-manager/apis/site.superedge.io"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*NodeGroup)(nil), (*sitesuperedgeio.NodeGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeGroup_To_sitesuperedgeio_NodeGroup(a.(*NodeGroup), b.(*sitesuperedgeio.NodeGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeGroup)(nil), (*NodeGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeGroup_To_v1alpha1_NodeGroup(a.(*sitesuperedgeio.NodeGroup), b.(*NodeGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeGroupList)(nil), (*sitesuperedgeio.NodeGroupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeGroupList_To_sitesuperedgeio_NodeGroupList(a.(*NodeGroupList), b.(*sitesuperedgeio.NodeGroupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeGroupList)(nil), (*NodeGroupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeGroupList_To_v1alpha1_NodeGroupList(a.(*sitesuperedgeio.NodeGroupList), b.(*NodeGroupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeGroupSpec)(nil), (*sitesuperedgeio.NodeGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeGroupSpec_To_sitesuperedgeio_NodeGroupSpec(a.(*NodeGroupSpec), b.(*sitesuperedgeio.NodeGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeGroupSpec)(nil), (*NodeGroupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(a.(*sitesuperedgeio.NodeGroupSpec), b.(*NodeGroupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeGroupStatus)(nil), (*sitesuperedgeio.NodeGroupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeGroupStatus_To_sitesuperedgeio_NodeGroupStatus(a.(*NodeGroupStatus), b.(*sitesuperedgeio.NodeGroupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeGroupStatus)(nil), (*NodeGroupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(a.(*sitesuperedgeio.NodeGroupStatus), b.(*NodeGroupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeUnit)(nil), (*sitesuperedgeio.NodeUnit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeUnit_To_sitesuperedgeio_NodeUnit(a.(*NodeUnit), b.(*sitesuperedgeio.NodeUnit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeUnit)(nil), (*NodeUnit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeUnit_To_v1alpha1_NodeUnit(a.(*sitesuperedgeio.NodeUnit), b.(*NodeUnit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeUnitList)(nil), (*sitesuperedgeio.NodeUnitList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeUnitList_To_sitesuperedgeio_NodeUnitList(a.(*NodeUnitList), b.(*sitesuperedgeio.NodeUnitList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeUnitList)(nil), (*NodeUnitList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeUnitList_To_v1alpha1_NodeUnitList(a.(*sitesuperedgeio.NodeUnitList), b.(*NodeUnitList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeUnitSpec)(nil), (*sitesuperedgeio.NodeUnitSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeUnitSpec_To_sitesuperedgeio_NodeUnitSpec(a.(*NodeUnitSpec), b.(*sitesuperedgeio.NodeUnitSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeUnitSpec)(nil), (*NodeUnitSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeUnitSpec_To_v1alpha1_NodeUnitSpec(a.(*sitesuperedgeio.NodeUnitSpec), b.(*NodeUnitSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeUnitStatus)(nil), (*sitesuperedgeio.NodeUnitStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeUnitStatus_To_sitesuperedgeio_NodeUnitStatus(a.(*NodeUnitStatus), b.(*sitesuperedgeio.NodeUnitStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.NodeUnitStatus)(nil), (*NodeUnitStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_NodeUnitStatus_To_v1alpha1_NodeUnitStatus(a.(*sitesuperedgeio.NodeUnitStatus), b.(*NodeUnitStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Selector)(nil), (*sitesuperedgeio.Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Selector_To_sitesuperedgeio_Selector(a.(*Selector), b.(*sitesuperedgeio.Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.Selector)(nil), (*Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_Selector_To_v1alpha1_Selector(a.(*sitesuperedgeio.Selector), b.(*Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SetNode)(nil), (*sitesuperedgeio.SetNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SetNode_To_sitesuperedgeio_SetNode(a.(*SetNode), b.(*sitesuperedgeio.SetNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.SetNode)(nil), (*SetNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_SetNode_To_v1alpha1_SetNode(a.(*sitesuperedgeio.SetNode), b.(*SetNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Workload)(nil), (*sitesuperedgeio.Workload)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Workload_To_sitesuperedgeio_Workload(a.(*Workload), b.(*sitesuperedgeio.Workload), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.Workload)(nil), (*Workload)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_Workload_To_v1alpha1_Workload(a.(*sitesuperedgeio.Workload), b.(*Workload), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadStatus)(nil), (*sitesuperedgeio.WorkloadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkloadStatus_To_sitesuperedgeio_WorkloadStatus(a.(*WorkloadStatus), b.(*sitesuperedgeio.WorkloadStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sitesuperedgeio.WorkloadStatus)(nil), (*WorkloadStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sitesuperedgeio_WorkloadStatus_To_v1alpha1_WorkloadStatus(a.(*sitesuperedgeio.WorkloadStatus), b.(*WorkloadStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_NodeGroup_To_sitesuperedgeio_NodeGroup(in *NodeGroup, out *sitesuperedgeio.NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NodeGroupSpec_To_sitesuperedgeio_NodeGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeGroupStatus_To_sitesuperedgeio_NodeGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NodeGroup_To_sitesuperedgeio_NodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroup_To_sitesuperedgeio_NodeGroup(in *NodeGroup, out *sitesuperedgeio.NodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroup_To_sitesuperedgeio_NodeGroup(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeGroup_To_v1alpha1_NodeGroup(in *sitesuperedgeio.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sitesuperedgeio_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sitesuperedgeio_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sitesuperedgeio_NodeGroup_To_v1alpha1_NodeGroup is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeGroup_To_v1alpha1_NodeGroup(in *sitesuperedgeio.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeGroup_To_v1alpha1_NodeGroup(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupList_To_sitesuperedgeio_NodeGroupList(in *NodeGroupList, out *sitesuperedgeio.NodeGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sitesuperedgeio.NodeGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NodeGroupList_To_sitesuperedgeio_NodeGroupList is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupList_To_sitesuperedgeio_NodeGroupList(in *NodeGroupList, out *sitesuperedgeio.NodeGroupList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupList_To_sitesuperedgeio_NodeGroupList(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeGroupList_To_v1alpha1_NodeGroupList(in *sitesuperedgeio.NodeGroupList, out *NodeGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NodeGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sitesuperedgeio_NodeGroupList_To_v1alpha1_NodeGroupList is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeGroupList_To_v1alpha1_NodeGroupList(in *sitesuperedgeio.NodeGroupList, out *NodeGroupList, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeGroupList_To_v1alpha1_NodeGroupList(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupSpec_To_sitesuperedgeio_NodeGroupSpec(in *NodeGroupSpec, out *sitesuperedgeio.NodeGroupSpec, s conversion.Scope) error {
	out.NodeUnits = *(*[]string)(unsafe.Pointer(&in.NodeUnits))
	out.Selector = (*sitesuperedgeio.Selector)(unsafe.Pointer(in.Selector))
	out.AutoFindNodeKeys = *(*[]string)(unsafe.Pointer(&in.AutoFindNodeKeys))
	out.Workload = *(*[]sitesuperedgeio.Workload)(unsafe.Pointer(&in.Workload))
	return nil
}

// Convert_v1alpha1_NodeGroupSpec_To_sitesuperedgeio_NodeGroupSpec is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupSpec_To_sitesuperedgeio_NodeGroupSpec(in *NodeGroupSpec, out *sitesuperedgeio.NodeGroupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupSpec_To_sitesuperedgeio_NodeGroupSpec(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in *sitesuperedgeio.NodeGroupSpec, out *NodeGroupSpec, s conversion.Scope) error {
	out.NodeUnits = *(*[]string)(unsafe.Pointer(&in.NodeUnits))
	out.Selector = (*Selector)(unsafe.Pointer(in.Selector))
	out.AutoFindNodeKeys = *(*[]string)(unsafe.Pointer(&in.AutoFindNodeKeys))
	out.Workload = *(*[]Workload)(unsafe.Pointer(&in.Workload))
	return nil
}

// Convert_sitesuperedgeio_NodeGroupSpec_To_v1alpha1_NodeGroupSpec is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in *sitesuperedgeio.NodeGroupSpec, out *NodeGroupSpec, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupStatus_To_sitesuperedgeio_NodeGroupStatus(in *NodeGroupStatus, out *sitesuperedgeio.NodeGroupStatus, s conversion.Scope) error {
	out.UnitNumber = in.UnitNumber
	out.NodeUnits = *(*[]string)(unsafe.Pointer(&in.NodeUnits))
	out.WorkloadStatus = *(*[]sitesuperedgeio.WorkloadStatus)(unsafe.Pointer(&in.WorkloadStatus))
	return nil
}

// Convert_v1alpha1_NodeGroupStatus_To_sitesuperedgeio_NodeGroupStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupStatus_To_sitesuperedgeio_NodeGroupStatus(in *NodeGroupStatus, out *sitesuperedgeio.NodeGroupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupStatus_To_sitesuperedgeio_NodeGroupStatus(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in *sitesuperedgeio.NodeGroupStatus, out *NodeGroupStatus, s conversion.Scope) error {
	out.UnitNumber = in.UnitNumber
	out.NodeUnits = *(*[]string)(unsafe.Pointer(&in.NodeUnits))
	out.WorkloadStatus = *(*[]WorkloadStatus)(unsafe.Pointer(&in.WorkloadStatus))
	return nil
}

// Convert_sitesuperedgeio_NodeGroupStatus_To_v1alpha1_NodeGroupStatus is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in *sitesuperedgeio.NodeGroupStatus, out *NodeGroupStatus, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeUnit_To_sitesuperedgeio_NodeUnit(in *NodeUnit, out *sitesuperedgeio.NodeUnit, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NodeUnitSpec_To_sitesuperedgeio_NodeUnitSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeUnitStatus_To_sitesuperedgeio_NodeUnitStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NodeUnit_To_sitesuperedgeio_NodeUnit is an autogenerated conversion function.
func Convert_v1alpha1_NodeUnit_To_sitesuperedgeio_NodeUnit(in *NodeUnit, out *sitesuperedgeio.NodeUnit, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeUnit_To_sitesuperedgeio_NodeUnit(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeUnit_To_v1alpha1_NodeUnit(in *sitesuperedgeio.NodeUnit, out *NodeUnit, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sitesuperedgeio_NodeUnitSpec_To_v1alpha1_NodeUnitSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_sitesuperedgeio_NodeUnitStatus_To_v1alpha1_NodeUnitStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_sitesuperedgeio_NodeUnit_To_v1alpha1_NodeUnit is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeUnit_To_v1alpha1_NodeUnit(in *sitesuperedgeio.NodeUnit, out *NodeUnit, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeUnit_To_v1alpha1_NodeUnit(in, out, s)
}

func autoConvert_v1alpha1_NodeUnitList_To_sitesuperedgeio_NodeUnitList(in *NodeUnitList, out *sitesuperedgeio.NodeUnitList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]sitesuperedgeio.NodeUnit, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_NodeUnit_To_sitesuperedgeio_NodeUnit(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_NodeUnitList_To_sitesuperedgeio_NodeUnitList is an autogenerated conversion function.
func Convert_v1alpha1_NodeUnitList_To_sitesuperedgeio_NodeUnitList(in *NodeUnitList, out *sitesuperedgeio.NodeUnitList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeUnitList_To_sitesuperedgeio_NodeUnitList(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeUnitList_To_v1alpha1_NodeUnitList(in *sitesuperedgeio.NodeUnitList, out *NodeUnitList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeUnit, len(*in))
		for i := range *in {
			if err := Convert_sitesuperedgeio_NodeUnit_To_v1alpha1_NodeUnit(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_sitesuperedgeio_NodeUnitList_To_v1alpha1_NodeUnitList is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeUnitList_To_v1alpha1_NodeUnitList(in *sitesuperedgeio.NodeUnitList, out *NodeUnitList, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeUnitList_To_v1alpha1_NodeUnitList(in, out, s)
}

func autoConvert_v1alpha1_NodeUnitSpec_To_sitesuperedgeio_NodeUnitSpec(in *NodeUnitSpec, out *sitesuperedgeio.NodeUnitSpec, s conversion.Scope) error {
	out.Type = sitesuperedgeio.NodeUnitType(in.Type)
	out.Unschedulable = in.Unschedulable
	out.Nodes = *(*[]string)(unsafe.Pointer(&in.Nodes))
	out.Selector = (*sitesuperedgeio.Selector)(unsafe.Pointer(in.Selector))
	if err := Convert_v1alpha1_SetNode_To_sitesuperedgeio_SetNode(&in.SetNode, &out.SetNode, s); err != nil {
		return err
	}
	// INFO: in.Taints opted out of conversion generation
	return nil
}

// Convert_v1alpha1_NodeUnitSpec_To_sitesuperedgeio_NodeUnitSpec is an autogenerated conversion function.
func Convert_v1alpha1_NodeUnitSpec_To_sitesuperedgeio_NodeUnitSpec(in *NodeUnitSpec, out *sitesuperedgeio.NodeUnitSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeUnitSpec_To_sitesuperedgeio_NodeUnitSpec(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeUnitSpec_To_v1alpha1_NodeUnitSpec(in *sitesuperedgeio.NodeUnitSpec, out *NodeUnitSpec, s conversion.Scope) error {
	out.Type = NodeUnitType(in.Type)
	out.Unschedulable = in.Unschedulable
	out.Nodes = *(*[]string)(unsafe.Pointer(&in.Nodes))
	out.Selector = (*Selector)(unsafe.Pointer(in.Selector))
	if err := Convert_sitesuperedgeio_SetNode_To_v1alpha1_SetNode(&in.SetNode, &out.SetNode, s); err != nil {
		return err
	}
	return nil
}

// Convert_sitesuperedgeio_NodeUnitSpec_To_v1alpha1_NodeUnitSpec is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeUnitSpec_To_v1alpha1_NodeUnitSpec(in *sitesuperedgeio.NodeUnitSpec, out *NodeUnitSpec, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeUnitSpec_To_v1alpha1_NodeUnitSpec(in, out, s)
}

func autoConvert_v1alpha1_NodeUnitStatus_To_sitesuperedgeio_NodeUnitStatus(in *NodeUnitStatus, out *sitesuperedgeio.NodeUnitStatus, s conversion.Scope) error {
	out.ReadyRate = in.ReadyRate
	out.ReadyNodes = *(*[]string)(unsafe.Pointer(&in.ReadyNodes))
	out.NotReadyNodes = *(*[]string)(unsafe.Pointer(&in.NotReadyNodes))
	return nil
}

// Convert_v1alpha1_NodeUnitStatus_To_sitesuperedgeio_NodeUnitStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeUnitStatus_To_sitesuperedgeio_NodeUnitStatus(in *NodeUnitStatus, out *sitesuperedgeio.NodeUnitStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeUnitStatus_To_sitesuperedgeio_NodeUnitStatus(in, out, s)
}

func autoConvert_sitesuperedgeio_NodeUnitStatus_To_v1alpha1_NodeUnitStatus(in *sitesuperedgeio.NodeUnitStatus, out *NodeUnitStatus, s conversion.Scope) error {
	out.ReadyRate = in.ReadyRate
	out.ReadyNodes = *(*[]string)(unsafe.Pointer(&in.ReadyNodes))
	out.NotReadyNodes = *(*[]string)(unsafe.Pointer(&in.NotReadyNodes))
	return nil
}

// Convert_sitesuperedgeio_NodeUnitStatus_To_v1alpha1_NodeUnitStatus is an autogenerated conversion function.
func Convert_sitesuperedgeio_NodeUnitStatus_To_v1alpha1_NodeUnitStatus(in *sitesuperedgeio.NodeUnitStatus, out *NodeUnitStatus, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_NodeUnitStatus_To_v1alpha1_NodeUnitStatus(in, out, s)
}

func autoConvert_v1alpha1_Selector_To_sitesuperedgeio_Selector(in *Selector, out *sitesuperedgeio.Selector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchExpressions = *(*[]v1.LabelSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1alpha1_Selector_To_sitesuperedgeio_Selector is an autogenerated conversion function.
func Convert_v1alpha1_Selector_To_sitesuperedgeio_Selector(in *Selector, out *sitesuperedgeio.Selector, s conversion.Scope) error {
	return autoConvert_v1alpha1_Selector_To_sitesuperedgeio_Selector(in, out, s)
}

func autoConvert_sitesuperedgeio_Selector_To_v1alpha1_Selector(in *sitesuperedgeio.Selector, out *Selector, s conversion.Scope) error {
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	out.MatchExpressions = *(*[]v1.LabelSelectorRequirement)(unsafe.Pointer(&in.MatchExpressions))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_sitesuperedgeio_Selector_To_v1alpha1_Selector is an autogenerated conversion function.
func Convert_sitesuperedgeio_Selector_To_v1alpha1_Selector(in *sitesuperedgeio.Selector, out *Selector, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_Selector_To_v1alpha1_Selector(in, out, s)
}

func autoConvert_v1alpha1_SetNode_To_sitesuperedgeio_SetNode(in *SetNode, out *sitesuperedgeio.SetNode, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.Taints = *(*[]corev1.Taint)(unsafe.Pointer(&in.Taints))
	return nil
}

// Convert_v1alpha1_SetNode_To_sitesuperedgeio_SetNode is an autogenerated conversion function.
func Convert_v1alpha1_SetNode_To_sitesuperedgeio_SetNode(in *SetNode, out *sitesuperedgeio.SetNode, s conversion.Scope) error {
	return autoConvert_v1alpha1_SetNode_To_sitesuperedgeio_SetNode(in, out, s)
}

func autoConvert_sitesuperedgeio_SetNode_To_v1alpha1_SetNode(in *sitesuperedgeio.SetNode, out *SetNode, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.Taints = *(*[]corev1.Taint)(unsafe.Pointer(&in.Taints))
	return nil
}

// Convert_sitesuperedgeio_SetNode_To_v1alpha1_SetNode is an autogenerated conversion function.
func Convert_sitesuperedgeio_SetNode_To_v1alpha1_SetNode(in *sitesuperedgeio.SetNode, out *SetNode, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_SetNode_To_v1alpha1_SetNode(in, out, s)
}

func autoConvert_v1alpha1_Workload_To_sitesuperedgeio_Workload(in *Workload, out *sitesuperedgeio.Workload, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = sitesuperedgeio.WorkloadType(in.Type)
	out.Selector = (*sitesuperedgeio.Selector)(unsafe.Pointer(in.Selector))
	return nil
}

// Convert_v1alpha1_Workload_To_sitesuperedgeio_Workload is an autogenerated conversion function.
func Convert_v1alpha1_Workload_To_sitesuperedgeio_Workload(in *Workload, out *sitesuperedgeio.Workload, s conversion.Scope) error {
	return autoConvert_v1alpha1_Workload_To_sitesuperedgeio_Workload(in, out, s)
}

func autoConvert_sitesuperedgeio_Workload_To_v1alpha1_Workload(in *sitesuperedgeio.Workload, out *Workload, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = WorkloadType(in.Type)
	out.Selector = (*Selector)(unsafe.Pointer(in.Selector))
	return nil
}

// Convert_sitesuperedgeio_Workload_To_v1alpha1_Workload is an autogenerated conversion function.
func Convert_sitesuperedgeio_Workload_To_v1alpha1_Workload(in *sitesuperedgeio.Workload, out *Workload, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_Workload_To_v1alpha1_Workload(in, out, s)
}

func autoConvert_v1alpha1_WorkloadStatus_To_sitesuperedgeio_WorkloadStatus(in *WorkloadStatus, out *sitesuperedgeio.WorkloadStatus, s conversion.Scope) error {
	out.WorkloadName = in.WorkloadName
	out.ReadyUnit = *(*[]string)(unsafe.Pointer(&in.ReadyUnit))
	out.NotReadyUnit = *(*[]string)(unsafe.Pointer(&in.NotReadyUnit))
	return nil
}

// Convert_v1alpha1_WorkloadStatus_To_sitesuperedgeio_WorkloadStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadStatus_To_sitesuperedgeio_WorkloadStatus(in *WorkloadStatus, out *sitesuperedgeio.WorkloadStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadStatus_To_sitesuperedgeio_WorkloadStatus(in, out, s)
}

func autoConvert_sitesuperedgeio_WorkloadStatus_To_v1alpha1_WorkloadStatus(in *sitesuperedgeio.WorkloadStatus, out *WorkloadStatus, s conversion.Scope) error {
	out.WorkloadName = in.WorkloadName
	out.ReadyUnit = *(*[]string)(unsafe.Pointer(&in.ReadyUnit))
	out.NotReadyUnit = *(*[]string)(unsafe.Pointer(&in.NotReadyUnit))
	return nil
}

// Convert_sitesuperedgeio_WorkloadStatus_To_v1alpha1_WorkloadStatus is an autogenerated conversion function.
func Convert_sitesuperedgeio_WorkloadStatus_To_v1alpha1_WorkloadStatus(in *sitesuperedgeio.WorkloadStatus, out *WorkloadStatus, s conversion.Scope) error {
	return autoConvert_sitesuperedgeio_WorkloadStatus_To_v1alpha1_WorkloadStatus(in, out, s)
}
