apiVersion: v1
kind: ConfigMap
metadata:
  name: tarsserver-config
data:
  TARS_LOCATOR: "tars.tarsregistry.QueryObj@tcp -h <部署tars-registry的节点的外网IP> -p 30015"
  TARS_REGISTRY: "tars.tarsregistry.Registry@tcp -h <部署tars-registry的节点的外网IP> -p 30016"
  TARS_NOTIFY: "tars.tarsnotify.NotifyObj@tcp -h <部署tars-notify的节点的外网IP> -p 30017"
