## Copyright 2020-2021 VMware, Inc. All Rights Reserved.
## source link: https://github.com/edgexfoundry/device-random
apiVersion: v1
kind: Service
metadata:
  name: edgex-device-random
  namespace: edgex
spec:
  type: NodePort
  selector:
    app: edgex-device-random
  ports:
    - name: http
      port: 49988
      protocol: TCP
      targetPort: 49988
      nodePort: 30088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-device-random
  namespace: edgex
spec:
  selector:
    matchLabels:
      app: edgex-device-random
  template:
    metadata:
      labels:
        app: edgex-device-random
    spec:
      hostname: edgex-device-random
      containers:
        - name: edgex-device-random
          image: edgexfoundry/docker-device-random-go:1.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 49988
          envFrom:
            - configMapRef:
                name: common-variables
          env:
            - name: Service_Host
              value: "edgex-device-random"
