## Copyright 2020-2021 VMware, Inc. All Rights Reserved.
## source link: https://github.com/edgexfoundry/app-service-configurable
apiVersion: v1
kind: Service
metadata:
  name: edgex-app-service-configurable-mqtt
  namespace: edgex
spec:
  type: NodePort
  selector:
    app: edgex-app-service-configurable-mqtt
  ports:
    - name: http
      port: 48101
      protocol: TCP
      targetPort: 48101
      nodePort: 30200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-app-service-configurable-mqtt
  namespace: edgex
spec:
  selector:
    matchLabels:
      app: edgex-app-service-configurable-mqtt
  template:
    metadata:
      labels:
        app: edgex-app-service-configurable-mqtt
    spec:
      hostname: edgex-app-service-configurable-mqtt
      containers:
        - name: edgex-app-service-configurable-mqtt
          image: edgexfoundry/docker-app-service-configurable:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 48101
          envFrom:
            - configMapRef:
                name: common-variables
          env:
            - name: edgex_profile
              value: "mqtt-export"
            - name: Service_Host
              value: "edgex-app-service-configurable-mqtt"
            - name: Service_Port
              value: "48101"
            - name: MessageBus_SubscribeHost_Host
              value: "edgex-core-data"
            - name: Binding_PublishTopic
              value: "events"
            - name: Writable_Pipeline_Functions_MQTTSend_Addressable_Address
              value: "broker.mqttdashboard.com"
            - name: Writable_Pipeline_Functions_MQTTSend_Addressable_Port
              value: "1883"
            - name: Writable_Pipeline_Functions_MQTTSend_Addressable_Protocol
              value: "tcp"
            - name: Writable_Pipeline_Functions_MQTTSend_Addressable_Publisher
              value: "edgex"
            - name: Writable_Pipeline_Functions_MQTTSend_Addressable_Topic
              value: "EdgeXEvents"
