---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apps-manager-service-account
  namespace: edge-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apps-manager-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - services
      - secrets
      - namespaces
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps.superedge.io
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apps-manager-cluster-role-binding
  namespace: edge-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apps-manager-cluster-role
subjects:
  - kind: ServiceAccount
    name: apps-manager-service-account
    namespace: edge-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-manager-config
  namespace: edge-system
data:
  kubeconfig-01.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://127.0.0.1:51003
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubeconfig.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1USXdOakF6TXpNeE1Wb1hEVE14TVRJd05EQXpNek14TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUxGCko4cnhIZnlOTCt2Wk5tTU8wMGttdGhGdit2K2l3eUF4TXh6OVFJREh6VjYzYmVBaDNoUlQ3cWJaS3F0Yys1Y28KY3MzNUVvTEIxL0l6RFNmdXhiRzh0dVZyQjQ1TnRMbjdIQ1ozZVRaWU9sYWZNYVdLRWRKM1V4N3pGV3FSdGpVWgorckpWOUlPL1M5VHVjQVNqM3MybS84VjY3REZsRzYvSzNLTFFrSkRoZ2tkcU15N0EzeThtV1FDVGxYRnNSb2sxCi95MVREZmxiaWRYbVFGcTRMaE1nMkM2aEtvTkZzVUZCbzE3VWUyNndXSEw1elpxK1N6TS9ySE82bXFWWjBCakgKbVQxRWlmZFdvMXFMaVpDR2lMelRSMVdlaFJ1VUhBTWZTOUJtVHFNdDkvUXpvUVIrdGI4UzdBaS9uNlViZTN6VApxUS9SMW5TeVhwd0l6Y0d0NGdzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJSnIxdkFzMDZHZHF5RmtSOFoyUjhLVFNQaVoKbHVJTFppcWJWTHBVNUtGY1Avc3dwdGd2N2ZIU3hZdEpkemVOcisvOU5JUEI1SGxOWGF6VWFGRW85L044V0tHRgpoVW90a1RMUjN0bzBCQXhzaFE5d09aRThCNXZKeW9NRUpJd2xHR1NiYnZWeWh3YnNoYU04WnZRZVpnVTN5b3J1Cm52aTZFbzVnYkxlSHJxcjBkWkFqUWdJWDlKZXhnVGpKTjR0VmRWVVhoVmN5L0M5dXpFNVg0TmVmQzlIanJvb2cKQkprNkQ2M2VLZzI0bFhueExlaUNmWmhMM1puTHYzOEdOdXkvOTVhMjh1eUkxSVgvckJEM0JiV1BvUnFkVW5NawpuZkV6SWhxSWtHUGhia2IrK0FiSDdDR3krZXRhVG5send2VDhpNnk1NjQ3TnUzVzlzUXdKQkRueENtST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://cls-7fost3fg.ccs.tencent-cloud.com
      name: cls-7fost3fg
    contexts:
    - context:
        cluster: cls-7fost3fg
        user: tinyuser1638761628476621055
      name: tinyuser1638761628476621055@cls-7fost3fg
    current-context: tinyuser1638761628476621055@cls-7fost3fg
    kind: Config
    preferences: {}
    users:
    - name: tinyuser1638761628476621055
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1RENDQWN5Z0F3SUJBZ0lJZEZ1a2drTnVudFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRFeU1EWXdNek16TVRGYUZ3MHpNVEV5TURRd016TXpORGhhTUNZeApKREFpQmdOVkJBTVRHM1JwYm5sMWMyVnlNVFl6T0RjMk1UWXlPRFEzTmpZeU1UQTFOVENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3BxMzJoRFMzQlZPUEpnc0lwbG1aelJaY1gzYnF1UTNsUVIKcU1vYzF3akkyb0JjTGIxTzNRTWFyR2VOQXBNK1BFUDUxWjduTEJxQVVXN1NxbHZFWm9MTml3QmRHK1Zic2cxaApGN1hMQ0FMckJ6WGpQblVhL0tVV0svU0U3NWlVMUx4R0N4cG5oWEhPQTJFQk5YQUlwNlNUNG5QTkNDUUNJRUtzClhXS1JtZ3VKNmp6b3RBSGswT2FBSVVaOUJ0OCs2MHFyMkU2YTFtQlY1WGZMbzhnc0xYdzBBbWUyVDY4M0JsZEwKaDdkRFl3Q3ZEbG5yUDg5QlZLR0ZlUXUzUHpMMFJHNnpuWWxTNkRTZ2VTL3hVa0ZwSDhTRUNzekFVcjdNVEREUgo2M2VremhDdVdNZWlZMURJTGN1Qi94LzBhOHdNNTdxdm9FME1VbmRrUDh2OWJCUU44eVVDQXdFQUFhTW5NQ1V3CkRnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUJaSHB2RFRXdEFlSWtVQ2tTVzNiTnRqMWtsaTRyaWtlT1dyUWdrMnBkNFVYaHprVk5sekdzSwpkTkJqRStxcjN0bnA0WWM0dDliZlo3anlvMVFjR1M1ejg2ZmVSYzRDbUFhSThMWTU1eGFYbXJNYmRaZ2w1K2EwCmFRaWY1VEFNOWdCc0drUDRVdUVLdERNbG5NNTFlcktMN2pzcStpZys0TEtySVArRFNpY1VjZksvUUY2TFJJSGEKSjRVWllxZFM2aXpRR0VNa0Y1YkdkN1UrUUhyamlIbTFINkdJWWdwaG9QaUdWa0FWZGJhTXdPVHppWXUwQlhjdQpabHRPbDA2U2h5cTJjMVJhblNFb2JtWDMrRkFyc1VCaThjUmhxZFlFaXVaMDY3QllUVHAvdEorS1ZDNDdvQm8xCkRXOE9sQS8zRHJkOWlLSW0xcURTdDZqRnFIbTdvLzVzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcW1yZmFFTkxjRlU0OG1Dd2ltV1puTkZseGZkdXE1RGVWQkdveWh6WENNamFnRnd0CnZVN2RBeHFzWjQwQ2t6NDhRL25WbnVjc0dvQlJidEtxVzhSbWdzMkxBRjBiNVZ1eURXRVh0Y3NJQXVzSE5lTSsKZFJyOHBSWXI5SVR2bUpUVXZFWUxHbWVGY2M0RFlRRTFjQWlucEpQaWM4MElKQUlnUXF4ZFlwR2FDNG5xUE9pMApBZVRRNW9BaFJuMEczejdyU3F2WVRwcldZRlhsZDh1anlDd3RmRFFDWjdaUHJ6Y0dWMHVIdDBOakFLOE9XZXMvCnowRlVvWVY1QzdjL012UkVick9kaVZMb05LQjVML0ZTUVdrZnhJUUt6TUJTdnN4TU1OSHJkNlRPRUs1WXg2SmoKVU1ndHk0SC9IL1JyekF6bnVxK2dUUXhTZDJRL3kvMXNGQTN6SlFJREFRQUJBb0lCQUNENjI4OW1ycFBIdW1TVgp0N1NnNHZDSlNhUGROYXE0TjM2WGlFM005UVI3TW1ZQzhNc2hGdjZCeS9taVBXeFhiL3hMdmo2cFNFeThwb1hHCitUY1hOQ3QrTWJkWlRZdStpaCt5dVk3eUF0UGx2aGg4cU5xcTVWZmhpWklobytpb2JOOGV3d2xTSFc0ZnkyR2IKaFVid05kbFEwVk5OeTVTRVlNL21ZWkF3MDFvRi9xbncxeHhGbzFGWUdJRVdmLzg4RmdTcGhlSDM3Z1lFNmhkZwp5VlR4dTZLUDNHekx1djd0YWdkMGFTaFVmVk1MRlplZmM1KzJsSHdnUjltWGZCdTNFL0UrMWZVYnlnbHJEQk5QCmJ3Y0dUMndiaTJFZE51QXRDVzVpTVduTlhQd2hsWjcvZXpoS2FpQUZKb3hhbnRnR1E0VVE2TUNHZXM2Q1pNcGsKc2VSUWtXVUNnWUVBMzQzSFFUNnN0OWk1S1NLQnlRMDAwMW8xdDhUdHJDZ3VTV2NiYkpEY1M5TVAzcEdKT2pldgpTbTlvNVlNZ2VEWjgyeHhJcnJuQndKYXdmNmZ2ZVE4dmMrSTJpM3J2ZFkrRVRGUVFVeGhCek9lTVY1WTRiakhMCktLb0RVNW96d0JhSmNGTDlxRGN1Z3RwaHl1bWVMai9GMXZQeCtlc2twMWswMjFwNHhrdFVWdk1DZ1lFQXd5YkwKWEVFczdJYjA1R0JRRTBHMzlTcWZTdC85TjRCMDlGTjdONUNMNE5qdGxPQnladEU5OWVZRSthc1hQTCtTSDg4YQpsQ3M3b2gzcE9EOHpCVEVxNVFKa0JIa2hGQWs1TmZSMERkMnlkM0wvNThLWmFjSzNtQ29SR3ZGNEduRHdTc000ClBCcU9hcVUvSjg4TXBNeUFwQk4rYW1LbHFJNEEwaGNGY0dxRHc0Y0NnWUVBalI0WWU4MHVobGRlZXVMM2ZvekIKbmZGQ0c2RktUdlNHVTN1c3lobWZscFhEWE1JT0dCdnlvVkEyclRyYkVrZURCV1dUVkFpYWtCSVBsR1hVTzEwawpuVWhkR2lzZVlkMllxLzRjMS9kbUFnemdnS0dwT1paaEltZy85VlJQK3ArL1hwSms0UDBFZFVHWm5kZGZMTjdBCjZuSFBlKzI5azQ0eVdZMkEwOXZWZjVVQ2dZQTUwOWtXOFVrNm5aTWJ5VjV4Rmx4SWplUzk3em05cEpjRGYybFgKd2NGeFUxYXpjdjd6Y0xXSGxDMk5QaUdZb3J2T0tUU2JDMlNVV1lDdVppdmNNZ0dmOHVGb1lleG5YNFJRZEt1ZgpJRDZ1SHFtdUo0QUdVdWpNY2txM1RTNWx4Mm1zL2NSQUt5NWdjNjhQUU05aVZpY1lkNTVTTUFFZXZWV0k2OEYwCjJsdEpLUUtCZ0gxUTdaNVJMTDJ1TzJ3a3NQL1hYUklLaTFxM0k5cGY5KzNIbXJiZUo2V3QyZmJWVUlXRU1wZ2IKUVhta2M5b2haUlN3R2Fpd0pqNUZHbVNkYTBpTUdrSThLdlpYTWFYelF2WVlHeDZvMXFqVTh0VmQyZ0Rrd3BFTAo5YXgvTFAyb2hJRHhNOGdqRkpWbEQva2I4aE5lYVQ3ZFF0K1FDamduRS8rU3M0SEszbVBGCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: apps-manager
  name: apps-manager
  namespace: edge-system
spec:
  selector:
    matchLabels:
      k8s-app: apps-manager
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        k8s-app: apps-manager
    spec:
      serviceAccount: apps-manager-service-account # todo
      serviceAccountName: apps-manager-service-account # todo
      priorityClassName: system-node-critical     # todo
      hostNetwork: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: cvm-r6faknja # TODO select edge node
      containers:
        - name: apps-manager
          image: ccr.ccs.tencentyun.com/superedge/apps-manager-amd64:v0.7.0
          imagePullPolicy: Always # todo IfNotPresent
          command:
            - /usr/local/bin/apps-manager
            - --kubeconfig=/var/lib/apps-manager/kubeconfig.conf
            - --master=127.0.0.1:51006
            - --hostname=$(NODE_NAME)
            - v=9
            # - --notify-channel-size=10000 # todo IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/apps-manager
              name: apps-manager-config
            - mountPath: /etc/kubernetes/manifests/
              name: kube-manifests
            - mountPath: /etc/kubernetes/edge-manifests/
              name: edge-manifests
      volumes:
        - configMap:
            defaultMode: 420
            name: apps-manager-config
          name: apps-manager-config
        - hostPath:
            path: /etc/kubernetes/edge-manifests/
            type: DirectoryOrCreate
          name: edge-manifests
        - hostPath:
            path: /etc/kubernetes/manifests/
            type: DirectoryOrCreate
          name: kube-manifests

