---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: edge-health-admission
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNakNDQWhvQ0NRQzVscVNtaHNnSk5UQU5CZ2txaGtpRzl3MEJBUXNGQURCYk1Rc3dDUVlEVlFRR0V3SkQKVGpFU01CQUdBMVVFQ0F3SlIzVmhibWRrYjI1bk1SRXdEd1lEVlFRSERBaFRhR1Z1ZW1obGJqRVFNQTRHQTFVRQpDZ3dIVkdWdVkyVnVkREVUTUJFR0ExVUVBd3dLYzNWd1pYSXRaV1JuWlRBZUZ3MHlNVEExTVRjeE16VXhNREZhCkZ3MHpOVEF4TWpReE16VXhNREZhTUZzeEN6QUpCZ05WQkFZVEFrTk9NUkl3RUFZRFZRUUlEQWxIZFdGdVoyUnYKYm1jeEVUQVBCZ05WQkFjTUNGTm9aVzU2YUdWdU1SQXdEZ1lEVlFRS0RBZFVaVzVqWlc1ME1STXdFUVlEVlFRRApEQXB6ZFhCbGNpMWxaR2RsTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzZnBzCm1SZ1RXS1l1VEhWaXEyZ1hPUTlZek1vdmdLaFlUUmdmem9xY0dIWVZuTVdTZ3IwQm5PS3dEVklCZ2dDZXo4eFQKbDhFWFYrTFV4anlhdW1BcVZKYTA0YUlrRTEvb3BkTEpSR1R6SXdZUGJweW15ZG9PRUhQK0d2UlcrcTNnRVlSNgpQSVRhNGM2bkV2RjBaTWI4MStOMjh0MDJmMjRDV3FjcnRkeUt5OGZaV2hobDZ1MHZaZEswMTVtK29LSzR0cUhWClNlN2FDNTl0dWVpYkk4ZDRlUW1YektKS2dUNTBZZHRrdkMzYlJLZm9OM2Zwa0UyT2tkaGF3UjBXaXFBWGhmWkEKTFRZQW81aHlndnlENDIya3NQbmdTQkZQa3NSNDhmK3lXNStsVmFVQjdoWllGRGRkSDYxRFdUMWpXNmlmS1VQQgpWcGx3UU5hRHNJdmNNZXdiWHdJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJHVzU1RjF4bHBBNW8wCldteHB1T28vQkx5ejdBbzdyOWNyVE5lcjJ3NGtzaUFwbEFJS2Y3Si9FZjJMTWw3cEdmcE5jUHF5QkpWaEtramEKVHcrTlQvU3k5V1BUeWpIMjRlVHRuL2MzZXlLMVhVbDFhZFhhWlNlQ0dPT2lQT0h1Y25BV3krQTRQU2lLdldmdApKTXF3bURnZDl3Vjh0WnhMUU9qT0FNR1dzZFhhdUtsbzY2cmVKby85QklJLzNoTTF2R2J4djNQeTh4cFBybGFQCm5idzlFOFJEV0hEbXppWjBzcjY2dE95aFBKR21aYXNWNG14R3dOczJaL3g1MnZUYTZtU3JRN3NBZUpkVmZYNUcKUGVFWnVwSjNWaEJrL2RWcG5OTVRpZDVRWGlINXFwZ1dTVGdFMFB5YmZNTGRSbmg0amhaS2ZBOGlCU1hJS25qSQpWN2FidmR6ZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: edge-system
        name: edge-health-admission
        path: /node-taint
    failurePolicy: Ignore
    matchPolicy: Exact
    name: node-taint.k8s.io
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - UPDATE
        resources:
          - nodes
        scope: '*'
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNakNDQWhvQ0NRQzVscVNtaHNnSk5UQU5CZ2txaGtpRzl3MEJBUXNGQURCYk1Rc3dDUVlEVlFRR0V3SkQKVGpFU01CQUdBMVVFQ0F3SlIzVmhibWRrYjI1bk1SRXdEd1lEVlFRSERBaFRhR1Z1ZW1obGJqRVFNQTRHQTFVRQpDZ3dIVkdWdVkyVnVkREVUTUJFR0ExVUVBd3dLYzNWd1pYSXRaV1JuWlRBZUZ3MHlNVEExTVRjeE16VXhNREZhCkZ3MHpOVEF4TWpReE16VXhNREZhTUZzeEN6QUpCZ05WQkFZVEFrTk9NUkl3RUFZRFZRUUlEQWxIZFdGdVoyUnYKYm1jeEVUQVBCZ05WQkFjTUNGTm9aVzU2YUdWdU1SQXdEZ1lEVlFRS0RBZFVaVzVqWlc1ME1STXdFUVlEVlFRRApEQXB6ZFhCbGNpMWxaR2RsTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzZnBzCm1SZ1RXS1l1VEhWaXEyZ1hPUTlZek1vdmdLaFlUUmdmem9xY0dIWVZuTVdTZ3IwQm5PS3dEVklCZ2dDZXo4eFQKbDhFWFYrTFV4anlhdW1BcVZKYTA0YUlrRTEvb3BkTEpSR1R6SXdZUGJweW15ZG9PRUhQK0d2UlcrcTNnRVlSNgpQSVRhNGM2bkV2RjBaTWI4MStOMjh0MDJmMjRDV3FjcnRkeUt5OGZaV2hobDZ1MHZaZEswMTVtK29LSzR0cUhWClNlN2FDNTl0dWVpYkk4ZDRlUW1YektKS2dUNTBZZHRrdkMzYlJLZm9OM2Zwa0UyT2tkaGF3UjBXaXFBWGhmWkEKTFRZQW81aHlndnlENDIya3NQbmdTQkZQa3NSNDhmK3lXNStsVmFVQjdoWllGRGRkSDYxRFdUMWpXNmlmS1VQQgpWcGx3UU5hRHNJdmNNZXdiWHdJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJHVzU1RjF4bHBBNW8wCldteHB1T28vQkx5ejdBbzdyOWNyVE5lcjJ3NGtzaUFwbEFJS2Y3Si9FZjJMTWw3cEdmcE5jUHF5QkpWaEtramEKVHcrTlQvU3k5V1BUeWpIMjRlVHRuL2MzZXlLMVhVbDFhZFhhWlNlQ0dPT2lQT0h1Y25BV3krQTRQU2lLdldmdApKTXF3bURnZDl3Vjh0WnhMUU9qT0FNR1dzZFhhdUtsbzY2cmVKby85QklJLzNoTTF2R2J4djNQeTh4cFBybGFQCm5idzlFOFJEV0hEbXppWjBzcjY2dE95aFBKR21aYXNWNG14R3dOczJaL3g1MnZUYTZtU3JRN3NBZUpkVmZYNUcKUGVFWnVwSjNWaEJrL2RWcG5OTVRpZDVRWGlINXFwZ1dTVGdFMFB5YmZNTGRSbmg0amhaS2ZBOGlCU1hJS25qSQpWN2FidmR6ZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: edge-system
        name: edge-health-admission
        path: /endpoint
    failurePolicy: Ignore
    matchPolicy: Exact
    name: endpoint.k8s.io
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - UPDATE
        resources:
          - endpoints
        scope: '*'
    sideEffects: None
    timeoutSeconds: 5
