
apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: lite-apiserver
  name: lite-apiserver
  namespace: kube-system
spec:
  containers:
    - command:
        - lite-apiserver
        - --ca-file=/etc/kubernetes/pki/ca.crt
        - --tls-cert-file=/etc/kubernetes/edge/lite-apiserver.crt
        - --tls-private-key-file=/etc/kubernetes/edge/lite-apiserver.key
        - --kube-apiserver-url={{.MasterIP}}
        - --kube-apiserver-port=6443
        - --port=51003
        - --tls-config-file=/etc/kubernetes/edge/tls.json
        - --v=4
        - --file-cache-path=/data/lite-apiserver/cache
        - --sync-duration=120
        - --timeout=3
      image: superedge/lite-apiserver:v0.1.0
      imagePullPolicy: IfNotPresent
      name: lite-apiserver
      volumeMounts:
        - mountPath: /etc/kubernetes/pki
          name: k8s-certs
        - mountPath: /etc/kubernetes/edge
          name: edge-certs
          readOnly: true
        - mountPath: /var/lib/kubelet/pki
          name: kubelet
          readOnly: true
        - mountPath: /data
          name: cache
  hostNetwork: true
  volumes:
    - hostPath:
        path: /var/lib/kubelet/pki
        type: DirectoryOrCreate
      name: kubelet
    - hostPath:
        path: /data
      name: cache
    - hostPath:
        path: /etc/kubernetes/pki
        name: DirectoryOrCreate
      name: k8s-certs
    - hostPath:
        path: /etc/kubernetes/edge
        name: DirectoryOrCreate
      name: edge-certs
status: {}
