---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: edge-system
data:
  nginx.conf: |
    worker_processes  1;
    events {
      worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        tcp_nopush     on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            location ~/(.*) {
                proxy_pass http://$1?args;
            }   
        }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-proxy
  namespace: edge-system
spec:
  selector:
    matchLabels:
      app: prometheus
      component: proxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        component: proxy
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 30021
          protocol: TCP
          name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

