---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: site-manager-service-account
  namespace: edge-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: site-manager-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - services
      - secrets
      - namespaces
      - events
    verbs:
      - "*"
  - apiGroups:
      - site.superedge.io
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: site-manager-cluster-role-binding
  namespace: edge-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: site-manager-cluster-role
subjects:
  - kind: ServiceAccount
    name: site-manager-service-account
    namespace: edge-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-manager-config
  namespace: edge-system
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-manager
  namespace: edge-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: site-manager
    spec:
      containers:
        - name: site-manager
          image: superedge.tencentcloudcr.com/superedge/site-manager:v0.7.0
          imagePullPolicy: Always
          command:
            - /usr/local/bin/site-manager
            - v=4
            #- --kubeconfig=/var/lib/site-manager-config/kubeconfig.conf
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data/edge
              name: hosts
            - mountPath: /var/lib/site-manager-config
              name: site-manager-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: site-manager-service-account
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - configMap:
            defaultMode: 420
            name: site-manager-config
          name: site-manager-config
        - hostPath:
            path: /data/edge
            type: DirectoryOrCreate
          name: hosts