
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statefulset-grid-daemon
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulset-grid-daemon
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - pods
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - superedge.io
    resources:
      - statefulsetgrids
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: statefulset-grid-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: statefulset-grid-daemon
subjects:
  - kind: ServiceAccount
    name: statefulset-grid-daemon
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: statefulset-grid-daemon
    addonmanager.kubernetes.io/mode: Reconcile
  name: statefulset-grid-daemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: statefulset-grid-daemon
  template:
    metadata:
      labels:
        k8s-app: statefulset-grid-daemon
    spec:
      serviceAccount: statefulset-grid-daemon
      serviceAccountName: statefulset-grid-daemon
      priorityClassName: system-node-critical
      hostNetwork: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux # TODO select edge node
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: statefulset-grid-daemon
          image: superedge/statefulset-grid-daemon:v0.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/statefulset-grid-daemon
            - --hostname=$(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data/edge
              name: hosts
      volumes:
        - hostPath:
            path: /data/edge
            type: DirectoryOrCreate
          name: hosts