apiVersion: superedge.io/v1
kind: DeploymentGrid
metadata:
  name: tarsnotify
  namespace: tars-system
spec:
  gridUniqKey: tars
  template:
    replicas: 1
    selector:
      matchLabels:
        app: tarsnotify
    template:
      metadata:
        labels:
          app: tarsnotify
      spec:
        tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        containers:
        - name: tarsnotify
          image: ccr.ccs.tencentyun.com/tarsbase/tarsnotify:v1.1.0
          ports:
          - containerPort: 13000
            protocol: TCP
            name: notify
          env:
          - name: TARS_LOCATOR
            valueFrom:
              configMapKeyRef:
                name: tars-configmap
                key: TARS_LOCATOR
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: tars-configmap
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: tars-configmap
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: tars-configmap
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              configMapKeyRef:
                name: tars-configmap
                key: DB_PASS
          readinessProbe:
              exec:
                command: ["tarscli", "hzcheck"]
              failureThreshold: 10
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["tarscli", "prestop"]
        terminationGracePeriodSeconds: 90
---
apiVersion: superedge.io/v1
kind: ServiceGrid
metadata:
  name: tarsnotify
  namespace: tars-system
spec:
  gridUniqKey: tars
  template:
    type: NodePort
    selector:
      app: tarsnotify
    ports:
    - port: 13000
      targetPort: 13000
      nodePort: 30017
      protocol: TCP

