name: verify

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: verify
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: verify go fmt
        run: sh hack/verify-gofmt.sh